
TCLFILES = colorbar.tcl pkgIndex.tcl
PKGVERSION = 1.0
DIR = $(PLUGINDIR)/noarch/tcl/colorbar$(PKGVERSION)

#
# Rules
#
bins:
win32bins:
dynlibs:
staticlibs: 
win32staticlibs: 

distrib:
	echo "Copying colorbar $(PKGVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(TCLFILES) $(DIR) 

	
