.SILENT:

VMFILES = autoionize.tcl autoionizegui.tcl pkgIndex.tcl ions.top
VMVERSION = 1.2
DIR = $(PLUGINDIR)/noarch/tcl/autoionize$(VMVERSION)

bins:
win32bins:
dynlibs:
staticlibs:
win32staticlibs:

distrib:
	@echo "Copying autoionize $(VMVERSION) files to $(DIR)"
	mkdir -p $(DIR) 
	cp $(VMFILES) $(DIR) 

	
